### ISSUE TITLE
JavaScript should be minified

### ISSUE THREAD

**Issue by coliff** [hnkansai/hnkansai.github.io#13]
for optimal performance the JS should be minified. could this be done at compilation time?

**Comment by benmurden** [comment]
Middleman has a build step for this, it seems.

https://middlemanapp.com/basics/build_and_deploy/

I'm used to Grunt/Gulp/Broccoli for build tools, but I don't see why there couldn't be a build step added if Middleman is not suitable.

**Comment by benmurden** [comment]
Resolved with https://github.com/hnkansai/hnkansai.github.io/commit/f0d33c66250fec16bebbac3e6923fc798635b407
